### ISSUE TITLE
Make Python2 executable

### ISSUE THREAD

**Issue by staneuski** [StasF1/turboCharger#3]
Выдаёт ошибку (Windows OS):

```bash
'python' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by StasF1** [comment]
Заходим в системные переменные и добавляем к уже существующей переменной _Path_ путь `C:\Python27` (или тот путь, где сохранён _Python27_).

**Comment by staneuski** [comment]
Заходим в системные переменные и добавляем к уже существующей переменной _Path_ путь `C:\Python27` (или тот путь, где сохранён _Python27_).
